### ISSUE TITLE
Create Event from Google Tag Manager using dataLayer - send to Google analytics

### ISSUE THREAD

**Issue by pranathi-ht** [holithemes/click-to-chat#10]
### Discussed in https://github.com/holithemes/click-to-chat/discussions/3

<div type='discussions-op-text'>

<sup>Originally posted by **bhvreddy** June  4, 2021</sup>
If Google Tag Manager is insalled on your website, Click to Chat plugin sends dataLayer Object. 

We can use this dataLayer object and can create a custom event. ( in Google Analytics, Facebook Pixel and many more places .. )

If you like to go in advance we can use variables. ( will discuss later )

### Create a trigger

Triggers -> new

and at 'Trigger configuration'  - at 'others' select - 'Custom Event'

![image](https://user-images.githubusercontent.com/4076309/120792655-7b81e580-c553-11eb-9a02-a4533a794608.png)

Name the event ( here we added - Click to Chat )

and at trigger fires on select 'some custom Events' 

and select as 'event' - 'contains' - Click to Chat

![image](https://user-images.githubusercontent.com/4076309/120792875-cc91d980-c553-11eb-8c95-ab89c4415676.png)

Save the trigger. 

### Tag

will create a tag and then assign it to Google Analytics 4

at 'Tags' - 'New'

At 'Tag configuration' select where to send the event

Here we will use Google analytics 4 (GA4) 

so will select 'Google Analytics - GA4 Event'

![image](https://user-images.githubusercontent.com/4076309/120793178-327e6100-c554-11eb-92a7-69388bbdab0d.png)

Congigure the GA4 tag and name the event

![image](https://user-images.githubusercontent.com/4076309/120794192-88073d80-c555-11eb-8d71-68d32ce6d3cf.png)

and then will select when to trigger this. 
as we created a trigger, will select that. 

![image](https://user-images.githubusercontent.com/4076309/120794407-d1f02380-c555-11eb-9e25-07221585dab9.png)

It looks like this.
![image](https://user-images.githubusercontent.com/4076309/120794447-e03e3f80-c555-11eb-8bb2-c83bf9943f84.png)

Save.

preview/submit and test it. 

Now When user clicks on WhatsApp icon/Button an event will create at Google analytics 

![image](https://user-images.githubusercontent.com/4076309/120794698-30b59d00-c556-11eb-8871-02dda9216b58.png)

'Click to Chat' event

![image](https://user-images.githubusercontent.com/4076309/120794738-3e6b2280-c556-11eb-8e48-58c2720209f4.png)

Now we know there is a click event. 

Anyhow google tag manager send some values to the event, like the page_location, page_title, .. 

Now will check how to get the WhatsApp Number and attach to Event

Click to Chat plugin sends some variables with the dataLayer.

`Variable key: Variable Value`

    `event: 'Click to Chat',
     type: 'chat',
     number: id,
     title: post_title,
     url: url,
     event_category: ga_category,
     event_label: ga_label,
     event_action: ga_action,`

The varaible values are dyanamic. we will use varaible key to get the value at GTM and send to Google Analytics.

### Variables

'Variables' at 'User Defined Variables' -> 'New'

At 'Variable Configuration' select - 'Data Layer Variable'

![image](https://user-images.githubusercontent.com/4076309/120796336-5643a600-c558-11eb-8e91-f3bbfc23b0b7.png)

( Click to Chat send multiple variables, here we will add number, type variable. )

Number: will get the WhatsApp number
Type:  chat/group/share.

and at 'Data Layer Variable Name' add the Variable Key - 'number'  

![image](https://user-images.githubusercontent.com/4076309/120796775-db2ebf80-c558-11eb-9e81-1fbff8c4a71a.png)

Save it.

and will add type variable.  (repeated the steps)

![image](https://user-images.githubusercontent.com/4076309/120797065-2e087700-c559-11eb-90bd-5f577fcf2abc.png)

Save it.

Will attach this variable to the event tag.

Go the tag where we created early. 

At Event Parameters will add the varaibles.

![4c4a9c11069443a1d14ca03b470dae9d](https://user-images.githubusercontent.com/4076309/120798602-3b266580-c55b-11eb-8a90-01872b82515c.gif)

Save it.

preview/submit and test. 

Now when user clicks on WhatsApp icon, button and event will send to Google Analytics. 

![image](https://user-images.githubusercontent.com/4076309/120877474-584b4a80-c5d4-11eb-8c33-e2e7a4e4ea6c.png)

Here we can notice the variables added to google analytics  - WhatsApp Number, Chat/Group/Share 
if we navigate to the Number we can check the number.

</div>

**Comment by bhvreddy** [comment]
docs with video: https://holithemes.com/plugins/click-to-chat/create-event-from-google-tag-manager-using-datalayer-send-to-google-analytics/
